import { ItemDefinition, ItemDefinitionSchema } from '../schemas/item';

export const ITEMS: Record<string, ItemDefinition> = {
  chili_pepper: ItemDefinitionSchema.parse({
    id: 'chili_pepper',
    nameKey: '朝天红辣椒',
    descriptionKey: '全武器伤害 +15%，元素灼烧伤害 +25%',
    tags: ['fire', 'crit'],
    rarity: 'common',
    cost: 8,
    maxStacks: 5,
    color: '#e76f51',
    assetKey: 'item_chili_pepper',
    modifiers: [
      { stat: 'damageMultiplier', value: 0.15, mode: 'flat' },
      { stat: 'elementalDamage', value: 3, mode: 'flat' },
    ],
  }),

  heavy_spices: ItemDefinitionSchema.parse({
    id: 'heavy_spices',
    nameKey: '重辣魔鬼粉',
    descriptionKey: '【有得有失】近战伤害 +8, 元素伤害 +5, 护甲 -2',
    tags: ['fire', 'cleaver'],
    rarity: 'rare',
    cost: 12,
    maxStacks: 3,
    color: '#ff5400',
    assetKey: 'item_chili_pepper',
    modifiers: [
      { stat: 'meleeDamage', value: 8, mode: 'flat' },
      { stat: 'elementalDamage', value: 5, mode: 'flat' },
      { stat: 'armor', value: -2, mode: 'flat' },
    ],
  }),

  ice_cube: ItemDefinitionSchema.parse({
    id: 'ice_cube',
    nameKey: '老窖碎冰块',
    descriptionKey: '角色护甲 +2，闪避率 +5%',
    tags: ['ice', 'defense'],
    rarity: 'common',
    cost: 8,
    maxStacks: 5,
    color: '#48cae4',
    assetKey: 'item_ice_cube',
    modifiers: [
      { stat: 'armor', value: 2, mode: 'flat' },
      { stat: 'dodge', value: 0.05, mode: 'flat' },
    ],
  }),

  aged_vinegar: ItemDefinitionSchema.parse({
    id: 'aged_vinegar',
    nameKey: '老坛十年陈醋',
    descriptionKey: '【有得有失】闪避率 +10%, 移速 +18, 最大生命 -10',
    tags: ['ice', 'speed'],
    rarity: 'rare',
    cost: 11,
    maxStacks: 3,
    color: '#2a9d8f',
    assetKey: 'item_potion',
    modifiers: [
      { stat: 'dodge', value: 0.1, mode: 'flat' },
      { stat: 'moveSpeed', value: 18, mode: 'flat' },
      { stat: 'maxHp', value: -10, mode: 'flat' },
    ],
  }),

  sesame_oil: ItemDefinitionSchema.parse({
    id: 'sesame_oil',
    nameKey: '纯香芝麻油',
    descriptionKey: '角色移动速度 +12，暴击率 +5%',
    tags: ['oil', 'speed'],
    rarity: 'common',
    cost: 8,
    maxStacks: 5,
    color: '#f4a261',
    assetKey: 'item_sesame_oil',
    modifiers: [
      { stat: 'moveSpeed', value: 12, mode: 'flat' },
      { stat: 'critChance', value: 0.05, mode: 'flat' },
    ],
  }),

  golden_spatula: ItemDefinitionSchema.parse({
    id: 'golden_spatula',
    nameKey: '纯金大炒勺',
    descriptionKey: '【有得有失】【收获】营收 +15, 幸运 +10, 全伤害 -8%',
    tags: ['economy', 'sugar'],
    rarity: 'epic',
    cost: 15,
    maxStacks: 3,
    color: '#ffd166',
    assetKey: 'item_sugar',
    modifiers: [
      { stat: 'harvest', value: 15, mode: 'flat' },
      { stat: 'luck', value: 10, mode: 'flat' },
      { stat: 'damageMultiplier', value: -0.08, mode: 'flat' },
    ],
  }),

  cane_sugar: ItemDefinitionSchema.parse({
    id: 'cane_sugar',
    nameKey: '古法红蔗糖',
    descriptionKey: '拾取范围 +30px，【收获】营收 +6',
    tags: ['sugar', 'economy'],
    rarity: 'common',
    cost: 8,
    maxStacks: 5,
    color: '#ffd166',
    assetKey: 'item_cane_sugar',
    modifiers: [
      { stat: 'pickupRadius', value: 30, mode: 'flat' },
      { stat: 'harvest', value: 6, mode: 'flat' },
    ],
  }),

  iron_stomach: ItemDefinitionSchema.parse({
    id: 'iron_stomach',
    nameKey: '暴食铁胃',
    descriptionKey: '【有得有失】最大生命 +30, 生命秒回 +3, 移速 -15',
    tags: ['defense', 'ferment'],
    rarity: 'epic',
    cost: 14,
    maxStacks: 3,
    color: '#06d6a0',
    assetKey: 'item_food',
    modifiers: [
      { stat: 'maxHp', value: 30, mode: 'flat' },
      { stat: 'hpRegen', value: 3, mode: 'flat' },
      { stat: 'moveSpeed', value: -15, mode: 'flat' },
    ],
  }),

  fermented_sauce: ItemDefinitionSchema.parse({
    id: 'fermented_sauce',
    nameKey: '特酿豆瓣酱',
    descriptionKey: '暴击伤害 +40%，近战伤害 +6',
    tags: ['ferment', 'crit'],
    rarity: 'rare',
    cost: 12,
    maxStacks: 3,
    color: '#9b2226',
    assetKey: 'item_fermented_sauce',
    modifiers: [
      { stat: 'critMultiplier', value: 0.4, mode: 'flat' },
      { stat: 'meleeDamage', value: 6, mode: 'flat' },
    ],
  }),

  bamboo_steamer: ItemDefinitionSchema.parse({
    id: 'bamboo_steamer',
    nameKey: '老竹小蒸笼',
    descriptionKey: '最大生命值 +25 点，帮厨工程 +3',
    tags: ['defense', 'summon'],
    rarity: 'rare',
    cost: 12,
    maxStacks: 3,
    color: '#d4a373',
    assetKey: 'item_bamboo_steamer',
    modifiers: [
      { stat: 'maxHp', value: 25, mode: 'flat' },
      { stat: 'engineering', value: 3, mode: 'flat' },
    ],
  }),

  garlic_clove: ItemDefinitionSchema.parse({
    id: 'garlic_clove',
    nameKey: '紫皮独头蒜',
    descriptionKey: '角色护甲 +2，生命秒回 +1',
    tags: ['defense', 'oil'],
    rarity: 'common',
    cost: 7,
    maxStacks: 4,
    color: '#e2ece9',
    assetKey: 'item_garlic_clove',
    modifiers: [
      { stat: 'armor', value: 2, mode: 'flat' },
      { stat: 'hpRegen', value: 1, mode: 'flat' },
    ],
  }),

  star_anise: ItemDefinitionSchema.parse({
    id: 'star_anise',
    nameKey: '阴阳八角茴',
    descriptionKey: '全武器攻击速度 +15%，远程伤害 +4',
    tags: ['speed', 'skewer'],
    rarity: 'rare',
    cost: 12,
    maxStacks: 3,
    color: '#8d0801',
    assetKey: 'item_star_anise',
    modifiers: [
      { stat: 'attackSpeedMultiplier', value: 0.15, mode: 'flat' },
      { stat: 'rangedDamage', value: 4, mode: 'flat' },
    ],
  }),

  dang_gui_herb: ItemDefinitionSchema.parse({
    id: 'dang_gui_herb',
    nameKey: '当归滋补草',
    descriptionKey: '生命窃取 +2，生命秒回 +2',
    tags: ['defense', 'ferment'],
    rarity: 'rare',
    cost: 12,
    maxStacks: 3,
    color: '#2a9d8f',
    assetKey: 'item_herb',
    modifiers: [
      { stat: 'lifesteal', value: 2, mode: 'flat' },
      { stat: 'hpRegen', value: 2, mode: 'flat' },
    ],
  }),

  wolfberry_wine: ItemDefinitionSchema.parse({
    id: 'wolfberry_wine',
    nameKey: '枸杞养生酒',
    descriptionKey: '击杀敌人必回 2 点生命值，最大生命 +20 点',
    tags: ['ferment', 'economy'],
    rarity: 'rare',
    cost: 14,
    maxStacks: 3,
    color: '#e76f51',
    assetKey: 'item_potion',
    modifiers: [
      { stat: 'maxHp', value: 20, mode: 'flat' },
    ],
  }),

  lucky_cat: ItemDefinitionSchema.parse({
    id: 'lucky_cat',
    nameKey: '招财金灵猫',
    descriptionKey: '【有得有失】幸运 +20, 【收获】营收 +10, 攻击速度 -8%',
    tags: ['economy', 'sugar'],
    rarity: 'epic',
    cost: 16,
    maxStacks: 3,
    color: '#ffd166',
    assetKey: 'item_sugar',
    modifiers: [
      { stat: 'luck', value: 20, mode: 'flat' },
      { stat: 'harvest', value: 10, mode: 'flat' },
      { stat: 'attackSpeedMultiplier', value: -0.08, mode: 'flat' },
    ],
  }),
};
