import { EnemyDefinition, EnemyDefinitionSchema } from '../schemas/enemy';

export const ENEMIES: Record<string, EnemyDefinition> = {
  hungry_ghost: EnemyDefinitionSchema.parse({
    id: 'hungry_ghost',
    nameKey: '饥饿游魂',
    category: 'normal',
    maxHp: 25,
    moveSpeed: 110,
    contactDamage: 8,
    radius: 13,
    knockbackResistance: 0.1,
    expValue: 1,
    ingredientChance: 0.12,
    ingredientValue: 1,
    color: '#8fa3a6',
    assetKey: 'enemy_hungry_ghost',
  }),

  spicy_slime: EnemyDefinitionSchema.parse({
    id: 'spicy_slime',
    nameKey: '麻辣泥怪',
    category: 'normal',
    maxHp: 45,
    moveSpeed: 85,
    contactDamage: 12,
    radius: 16,
    knockbackResistance: 0.15,
    expValue: 2,
    ingredientChance: 0.2,
    ingredientValue: 1,
    color: '#e76f51',
    assetKey: 'enemy_spicy_slime',
  }),

  lantern_spirit: EnemyDefinitionSchema.parse({
    id: 'lantern_spirit',
    nameKey: '引魂灯笼',
    category: 'normal',
    maxHp: 35,
    moveSpeed: 145,
    contactDamage: 10,
    radius: 12,
    knockbackResistance: 0.05,
    expValue: 2,
    ingredientChance: 0.25,
    ingredientValue: 1,
    color: '#ffd166',
    assetKey: 'enemy_lantern_spirit',
  }),

  grease_goblin: EnemyDefinitionSchema.parse({
    id: 'grease_goblin',
    nameKey: '地沟油怪',
    category: 'normal',
    maxHp: 75,
    moveSpeed: 70,
    contactDamage: 15,
    radius: 18,
    knockbackResistance: 0.3,
    expValue: 3,
    ingredientChance: 0.3,
    ingredientValue: 2,
    color: '#588157',
    assetKey: 'enemy_grease_goblin',
  }),

  skewer_thief: EnemyDefinitionSchema.parse({
    id: 'skewer_thief',
    nameKey: '偷串鼠妖',
    category: 'normal',
    maxHp: 30,
    moveSpeed: 180,
    contactDamage: 9,
    radius: 11,
    knockbackResistance: 0.05,
    expValue: 2,
    ingredientChance: 0.4,
    ingredientValue: 2,
    color: '#264653',
    assetKey: 'enemy_skewer_thief',
  }),

  steam_phantom: EnemyDefinitionSchema.parse({
    id: 'steam_phantom',
    nameKey: '蒸汽魅影',
    category: 'normal',
    maxHp: 55,
    moveSpeed: 125,
    contactDamage: 14,
    radius: 14,
    knockbackResistance: 0.2,
    expValue: 3,
    ingredientChance: 0.25,
    ingredientValue: 2,
    color: '#a8dadc',
    assetKey: 'enemy_steam_phantom',
  }),

  giant_bao_demon: EnemyDefinitionSchema.parse({
    id: 'giant_bao_demon',
    nameKey: '大包子妖魔',
    category: 'elite',
    maxHp: 450,
    moveSpeed: 90,
    contactDamage: 22,
    radius: 26,
    knockbackResistance: 0.5,
    expValue: 15,
    ingredientChance: 1.0,
    ingredientValue: 10,
    color: '#f4a261',
    assetKey: 'enemy_giant_bao_demon',
  }),

  flame_pot_guard: EnemyDefinitionSchema.parse({
    id: 'flame_pot_guard',
    nameKey: '火锅煞将',
    category: 'elite',
    maxHp: 700,
    moveSpeed: 105,
    contactDamage: 28,
    radius: 28,
    knockbackResistance: 0.6,
    expValue: 25,
    ingredientChance: 1.0,
    ingredientValue: 15,
    color: '#d62828',
    assetKey: 'enemy_flame_pot_guard',
  }),

  night_glutton_king: EnemyDefinitionSchema.parse({
    id: 'night_glutton_king',
    nameKey: '夜市饕餮王',
    category: 'boss',
    maxHp: 3200,
    moveSpeed: 115,
    contactDamage: 38,
    radius: 40,
    knockbackResistance: 0.85,
    expValue: 100,
    ingredientChance: 1.0,
    ingredientValue: 50,
    color: '#7209b7',
    assetKey: 'enemy_night_glutton_king',
  }),
};
