import { EnemyDefinition, EnemyDefinitionSchema } from '../schemas/enemy';

export const ENEMIES: Record<string, EnemyDefinition> = {
  // 6 种普通小怪
  hungry_ghost: EnemyDefinitionSchema.parse({
    id: 'hungry_ghost',
    nameKey: 'enemy.hungry_ghost.name',
    category: 'normal',
    maxHp: 25,
    moveSpeed: 70,
    radius: 12,
    contactDamage: 8,
    knockbackResistance: 0.1,
    expValue: 10,
    ingredientChance: 0.25,
    ingredientValue: 1,
    color: '#83c5be',
    assetKey: 'enemy_hungry_ghost',
    behaviors: ['chase'],
  }),

  spicy_slime: EnemyDefinitionSchema.parse({
    id: 'spicy_slime',
    nameKey: 'enemy.spicy_slime.name',
    category: 'normal',
    maxHp: 50,
    moveSpeed: 45,
    radius: 16,
    contactDamage: 12,
    knockbackResistance: 0.4,
    expValue: 18,
    ingredientChance: 0.35,
    ingredientValue: 1,
    color: '#e76f51',
    assetKey: 'enemy_spicy_slime',
    behaviors: ['chase'],
  }),

  lantern_spirit: EnemyDefinitionSchema.parse({
    id: 'lantern_spirit',
    nameKey: 'enemy.lantern_spirit.name',
    category: 'normal',
    maxHp: 20,
    moveSpeed: 110,
    radius: 11,
    contactDamage: 10,
    knockbackResistance: 0.05,
    expValue: 15,
    ingredientChance: 0.2,
    ingredientValue: 1,
    color: '#ffd166',
    assetKey: 'enemy_lantern_spirit',
    behaviors: ['chase_fast'],
  }),

  grease_goblin: EnemyDefinitionSchema.parse({
    id: 'grease_goblin',
    nameKey: 'enemy.grease_goblin.name',
    category: 'normal',
    maxHp: 65,
    moveSpeed: 60,
    radius: 14,
    contactDamage: 14,
    knockbackResistance: 0.25,
    expValue: 24,
    ingredientChance: 0.4,
    ingredientValue: 2,
    color: '#588157',
    assetKey: 'enemy_grease_goblin',
    behaviors: ['chase'],
  }),

  skewer_thief: EnemyDefinitionSchema.parse({
    id: 'skewer_thief',
    nameKey: 'enemy.skewer_thief.name',
    category: 'normal',
    maxHp: 35,
    moveSpeed: 135,
    radius: 10,
    contactDamage: 10,
    knockbackResistance: 0.0,
    expValue: 20,
    ingredientChance: 0.3,
    ingredientValue: 1,
    color: '#f4a261',
    assetKey: 'enemy_skewer_thief',
    behaviors: ['chase_fast'],
  }),

  steam_phantom: EnemyDefinitionSchema.parse({
    id: 'steam_phantom',
    nameKey: 'enemy.steam_phantom.name',
    category: 'normal',
    maxHp: 80,
    moveSpeed: 55,
    radius: 15,
    contactDamage: 16,
    knockbackResistance: 0.3,
    expValue: 30,
    ingredientChance: 0.45,
    ingredientValue: 2,
    color: '#d8e2dc',
    assetKey: 'enemy_steam_phantom',
    behaviors: ['chase'],
  }),

  // 2 种精英怪
  giant_bao_demon: EnemyDefinitionSchema.parse({
    id: 'giant_bao_demon',
    nameKey: 'enemy.giant_bao_demon.name',
    category: 'elite',
    maxHp: 450,
    moveSpeed: 50,
    radius: 28,
    contactDamage: 25,
    knockbackResistance: 0.75,
    expValue: 150,
    ingredientChance: 1.0,
    ingredientValue: 10,
    color: '#ffb703',
    assetKey: 'enemy_giant_bao_demon',
    behaviors: ['chase', 'stomp'],
  }),

  flame_pot_guard: EnemyDefinitionSchema.parse({
    id: 'flame_pot_guard',
    nameKey: 'enemy.flame_pot_guard.name',
    category: 'elite',
    maxHp: 600,
    moveSpeed: 75,
    radius: 26,
    contactDamage: 30,
    knockbackResistance: 0.8,
    expValue: 200,
    ingredientChance: 1.0,
    ingredientValue: 15,
    color: '#d62828',
    assetKey: 'enemy_flame_pot_guard',
    behaviors: ['chase', 'charge'],
  }),

  // 1 个最终 Boss
  night_glutton_king: EnemyDefinitionSchema.parse({
    id: 'night_glutton_king',
    nameKey: 'enemy.night_glutton_king.name',
    category: 'boss',
    maxHp: 2400,
    moveSpeed: 65,
    radius: 42,
    contactDamage: 40,
    knockbackResistance: 0.95,
    expValue: 1000,
    ingredientChance: 1.0,
    ingredientValue: 50,
    color: '#7209b7',
    assetKey: 'enemy_night_glutton_king',
    behaviors: ['boss_barrage', 'boss_summon', 'boss_slam'],
  }),
};
