import { WeaponDefinition, WeaponDefinitionSchema } from '../schemas/weapon';

export const WEAPONS: Record<string, WeaponDefinition> = {
  iron_wok: WeaponDefinitionSchema.parse({
    id: 'iron_wok',
    nameKey: 'weapon.iron_wok.name',
    descriptionKey: 'weapon.iron_wok.desc',
    tags: ['wok', 'melee', 'defense'],
    attackPattern: 'arc',
    targeting: 'forward',
    rarity: 'common',
    cost: 10,
    color: '#e07a5f',
    assetKey: 'weapon_iron_wok',
    levels: [
      {
        level: 1,
        descriptionKey: 'weapon.iron_wok.lvl1',
        damage: 28,
        cooldownMs: 900,
        projectileCount: 1,
        projectileSpeed: 0,
        pierce: 999,
        range: 110,
        durationMs: 250,
        radius: 75,
        effects: [{ type: 'knockback', value: 160 }],
      },
      {
        level: 2,
        descriptionKey: 'weapon.iron_wok.lvl2',
        damage: 42,
        cooldownMs: 800,
        projectileCount: 1,
        projectileSpeed: 0,
        pierce: 999,
        range: 130,
        durationMs: 280,
        radius: 90,
        effects: [{ type: 'knockback', value: 200 }],
      },
      {
        level: 3,
        descriptionKey: 'weapon.iron_wok.lvl3',
        damage: 65,
        cooldownMs: 700,
        projectileCount: 1,
        projectileSpeed: 0,
        pierce: 999,
        range: 150,
        durationMs: 300,
        radius: 105,
        effects: [
          { type: 'knockback', value: 240 },
          { type: 'burn', value: 8, durationMs: 2000, tickIntervalMs: 500 },
        ],
      },
    ],
  }),

  cleaver: WeaponDefinitionSchema.parse({
    id: 'cleaver',
    nameKey: 'weapon.cleaver.name',
    descriptionKey: 'weapon.cleaver.desc',
    tags: ['cleaver', 'projectile', 'crit'],
    attackPattern: 'projectile',
    targeting: 'nearest',
    rarity: 'common',
    cost: 10,
    color: '#f4a261',
    assetKey: 'weapon_cleaver',
    levels: [
      {
        level: 1,
        descriptionKey: 'weapon.cleaver.lvl1',
        damage: 22,
        cooldownMs: 750,
        projectileCount: 1,
        projectileSpeed: 380,
        pierce: 2,
        range: 350,
        durationMs: 1200,
        radius: 14,
        effects: [{ type: 'knockback', value: 60 }],
      },
      {
        level: 2,
        descriptionKey: 'weapon.cleaver.lvl2',
        damage: 32,
        cooldownMs: 650,
        projectileCount: 2,
        projectileSpeed: 420,
        pierce: 3,
        range: 400,
        durationMs: 1400,
        radius: 16,
        effects: [{ type: 'knockback', value: 80 }],
      },
      {
        level: 3,
        descriptionKey: 'weapon.cleaver.lvl3',
        damage: 48,
        cooldownMs: 550,
        projectileCount: 3,
        projectileSpeed: 460,
        pierce: 4,
        range: 450,
        durationMs: 1600,
        radius: 18,
        effects: [{ type: 'knockback', value: 100 }],
      },
    ],
  }),

  bamboo_skewer: WeaponDefinitionSchema.parse({
    id: 'bamboo_skewer',
    nameKey: 'weapon.bamboo_skewer.name',
    descriptionKey: 'weapon.bamboo_skewer.desc',
    tags: ['skewer', 'pierce', 'crit'],
    attackPattern: 'pierceLine',
    targeting: 'nearest',
    rarity: 'common',
    cost: 10,
    color: '#e9c46a',
    assetKey: 'weapon_bamboo_skewer',
    levels: [
      {
        level: 1,
        descriptionKey: 'weapon.bamboo_skewer.lvl1',
        damage: 18,
        cooldownMs: 600,
        projectileCount: 1,
        projectileSpeed: 520,
        pierce: 99,
        range: 420,
        durationMs: 900,
        radius: 8,
        effects: [{ type: 'knockback', value: 40 }],
      },
      {
        level: 2,
        descriptionKey: 'weapon.bamboo_skewer.lvl2',
        damage: 28,
        cooldownMs: 500,
        projectileCount: 2,
        projectileSpeed: 580,
        pierce: 99,
        range: 480,
        durationMs: 950,
        radius: 9,
        effects: [{ type: 'knockback', value: 50 }],
      },
      {
        level: 3,
        descriptionKey: 'weapon.bamboo_skewer.lvl3',
        damage: 42,
        cooldownMs: 400,
        projectileCount: 3,
        projectileSpeed: 640,
        pierce: 99,
        range: 540,
        durationMs: 1000,
        radius: 10,
        effects: [{ type: 'knockback', value: 60 }],
      },
    ],
  }),

  stove_flame: WeaponDefinitionSchema.parse({
    id: 'stove_flame',
    nameKey: 'weapon.stove_flame.name',
    descriptionKey: 'weapon.stove_flame.desc',
    tags: ['fire', 'area'],
    attackPattern: 'area',
    targeting: 'random',
    rarity: 'rare',
    cost: 14,
    color: '#e76f51',
    assetKey: 'weapon_stove_flame',
    levels: [
      {
        level: 1,
        descriptionKey: 'weapon.stove_flame.lvl1',
        damage: 12,
        cooldownMs: 1600,
        projectileCount: 1,
        projectileSpeed: 0,
        pierce: 999,
        range: 200,
        durationMs: 2500,
        radius: 65,
        effects: [{ type: 'burn', value: 6, durationMs: 2000, tickIntervalMs: 400 }],
      },
      {
        level: 2,
        descriptionKey: 'weapon.stove_flame.lvl2',
        damage: 20,
        cooldownMs: 1400,
        projectileCount: 2,
        projectileSpeed: 0,
        pierce: 999,
        range: 220,
        durationMs: 3000,
        radius: 80,
        effects: [{ type: 'burn', value: 10, durationMs: 2500, tickIntervalMs: 400 }],
      },
      {
        level: 3,
        descriptionKey: 'weapon.stove_flame.lvl3',
        damage: 32,
        cooldownMs: 1200,
        projectileCount: 3,
        projectileSpeed: 0,
        pierce: 999,
        range: 250,
        durationMs: 3500,
        radius: 95,
        effects: [{ type: 'burn', value: 15, durationMs: 3000, tickIntervalMs: 350 }],
      },
    ],
  }),

  seasoning_jar: WeaponDefinitionSchema.parse({
    id: 'seasoning_jar',
    nameKey: 'weapon.seasoning_jar.name',
    descriptionKey: 'weapon.seasoning_jar.desc',
    tags: ['orbit', 'defense'],
    attackPattern: 'orbit',
    targeting: 'forward',
    rarity: 'rare',
    cost: 14,
    color: '#2a9d8f',
    assetKey: 'weapon_seasoning_jar',
    levels: [
      {
        level: 1,
        descriptionKey: 'weapon.seasoning_jar.lvl1',
        damage: 20,
        cooldownMs: 3000,
        projectileCount: 2,
        projectileSpeed: 2.2, // 旋转角速度 rad/s
        pierce: 999,
        range: 90, // 旋转半径
        durationMs: 999999,
        radius: 15,
        effects: [{ type: 'knockback', value: 80 }],
      },
      {
        level: 2,
        descriptionKey: 'weapon.seasoning_jar.lvl2',
        damage: 32,
        cooldownMs: 3000,
        projectileCount: 3,
        projectileSpeed: 2.8,
        pierce: 999,
        range: 105,
        durationMs: 999999,
        radius: 17,
        effects: [{ type: 'knockback', value: 110 }],
      },
      {
        level: 3,
        descriptionKey: 'weapon.seasoning_jar.lvl3',
        damage: 46,
        cooldownMs: 3000,
        projectileCount: 4,
        projectileSpeed: 3.4,
        pierce: 999,
        range: 120,
        durationMs: 999999,
        radius: 19,
        effects: [{ type: 'knockback', value: 140 }],
      },
    ],
  }),

  service_bell: WeaponDefinitionSchema.parse({
    id: 'service_bell',
    nameKey: 'weapon.service_bell.name',
    descriptionKey: 'weapon.service_bell.desc',
    tags: ['summon', 'economy'],
    attackPattern: 'summon',
    targeting: 'nearest',
    rarity: 'epic',
    cost: 18,
    color: '#9d4edd',
    assetKey: 'weapon_service_bell',
    levels: [
      {
        level: 1,
        descriptionKey: 'weapon.service_bell.lvl1',
        damage: 16,
        cooldownMs: 3500,
        projectileCount: 1,
        projectileSpeed: 160,
        pierce: 999,
        range: 260,
        durationMs: 6000,
        radius: 20,
        effects: [{ type: 'knockback', value: 50 }],
      },
      {
        level: 2,
        descriptionKey: 'weapon.service_bell.lvl2',
        damage: 26,
        cooldownMs: 3000,
        projectileCount: 2,
        projectileSpeed: 180,
        pierce: 999,
        range: 300,
        durationMs: 7000,
        radius: 22,
        effects: [{ type: 'knockback', value: 70 }],
      },
      {
        level: 3,
        descriptionKey: 'weapon.service_bell.lvl3',
        damage: 40,
        cooldownMs: 2500,
        projectileCount: 3,
        projectileSpeed: 210,
        pierce: 999,
        range: 340,
        durationMs: 8000,
        radius: 24,
        effects: [{ type: 'knockback', value: 90 }],
      },
    ],
  }),
};
