import { WeaponDefinition, WeaponDefinitionSchema } from '../schemas/weapon';

export const WEAPONS: Record<string, WeaponDefinition> = {
  iron_wok: WeaponDefinitionSchema.parse({
    id: 'iron_wok',
    nameKey: '厚重铁锅',
    descriptionKey: '厚重大铁锅，近战扇面横扫击退周围妖怪',
    tags: ['wok', 'melee', 'defense'],
    attackPattern: 'arc',
    targeting: 'nearest',
    rarity: 'common',
    cost: 10,
    color: '#e07a5f',
    assetKey: 'weapon_iron_wok',
    levels: [
      {
        level: 1,
        descriptionKey: '近战扇面挥舞，造成 28 伤害与强力击退',
        damage: 28,
        cooldownMs: 900,
        projectileCount: 1,
        projectileSpeed: 0,
        pierce: 999,
        range: 110,
        durationMs: 250,
        radius: 75,
        effects: [{ type: 'knockback', value: 160 }],
      },
      {
        level: 2,
        descriptionKey: '铁锅范围扩大，伤害提升至 42，击退增强',
        damage: 42,
        cooldownMs: 800,
        projectileCount: 1,
        projectileSpeed: 0,
        pierce: 999,
        range: 130,
        durationMs: 280,
        radius: 90,
        effects: [{ type: 'knockback', value: 200 }],
      },
      {
        level: 3,
        descriptionKey: '铁锅附带爆炒烈火，造成 65 伤害并点燃敌人',
        damage: 65,
        cooldownMs: 700,
        projectileCount: 1,
        projectileSpeed: 0,
        pierce: 999,
        range: 150,
        durationMs: 300,
        radius: 105,
        effects: [
          { type: 'knockback', value: 240 },
          { type: 'burn', value: 8, durationMs: 2000, tickIntervalMs: 500 },
        ],
      },
    ],
  }),

  cleaver: WeaponDefinitionSchema.parse({
    id: 'cleaver',
    nameKey: '精钢菜刀',
    descriptionKey: '飞掷旋转菜刀，穿透斩割沿途敌人',
    tags: ['cleaver', 'projectile', 'crit'],
    attackPattern: 'projectile',
    targeting: 'nearest',
    rarity: 'common',
    cost: 10,
    color: '#f4a261',
    assetKey: 'weapon_cleaver',
    levels: [
      {
        level: 1,
        descriptionKey: '向最近敌人飞掷 1 把菜刀，造成 22 伤害并穿透 2 名敌人',
        damage: 22,
        cooldownMs: 750,
        projectileCount: 1,
        projectileSpeed: 380,
        pierce: 2,
        range: 350,
        durationMs: 1200,
        radius: 14,
        effects: [{ type: 'knockback', value: 60 }],
      },
      {
        level: 2,
        descriptionKey: '飞刀数量 +1，伤害提升至 32，穿透 +1',
        damage: 32,
        cooldownMs: 650,
        projectileCount: 2,
        projectileSpeed: 420,
        pierce: 3,
        range: 400,
        durationMs: 1400,
        radius: 16,
        effects: [{ type: 'knockback', value: 80 }],
      },
      {
        level: 3,
        descriptionKey: '飞刀数量 +1 (共3把)，伤害 48，弹速提升且暴击大幅提高',
        damage: 48,
        cooldownMs: 550,
        projectileCount: 3,
        projectileSpeed: 460,
        pierce: 4,
        range: 450,
        durationMs: 1600,
        radius: 18,
        effects: [{ type: 'knockback', value: 100 }],
      },
    ],
  }),

  bamboo_skewer: WeaponDefinitionSchema.parse({
    id: 'bamboo_skewer',
    nameKey: '穿心竹签',
    descriptionKey: '高速穿刺直线弹道，洞穿前行妖魔',
    tags: ['skewer', 'pierce', 'crit'],
    attackPattern: 'pierceLine',
    targeting: 'nearest',
    rarity: 'common',
    cost: 10,
    color: '#e9c46a',
    assetKey: 'weapon_bamboo_skewer',
    levels: [
      {
        level: 1,
        descriptionKey: '射出高速竹签疾刺，造成 18 伤害并无限穿透直线敌人',
        damage: 18,
        cooldownMs: 600,
        projectileCount: 1,
        projectileSpeed: 520,
        pierce: 99,
        range: 420,
        durationMs: 900,
        radius: 8,
        effects: [{ type: 'knockback', value: 40 }],
      },
      {
        level: 2,
        descriptionKey: '竹签数量 +1 (双发突刺)，伤害提升至 28',
        damage: 28,
        cooldownMs: 500,
        projectileCount: 2,
        projectileSpeed: 580,
        pierce: 99,
        range: 480,
        durationMs: 950,
        radius: 9,
        effects: [{ type: 'knockback', value: 50 }],
      },
      {
        level: 3,
        descriptionKey: '竹签数量 +1 (三连穿心)，伤害 42，攻击间隔大幅缩短',
        damage: 42,
        cooldownMs: 400,
        projectileCount: 3,
        projectileSpeed: 640,
        pierce: 99,
        range: 540,
        durationMs: 1000,
        radius: 10,
        effects: [{ type: 'knockback', value: 60 }],
      },
    ],
  }),

  stove_flame: WeaponDefinitionSchema.parse({
    id: 'stove_flame',
    nameKey: '猛火炉灶',
    descriptionKey: '在地面喷射持续灼烧的炽热火域',
    tags: ['fire', 'area'],
    attackPattern: 'area',
    targeting: 'nearest',
    rarity: 'rare',
    cost: 14,
    color: '#e76f51',
    assetKey: 'weapon_stove_flame',
    levels: [
      {
        level: 1,
        descriptionKey: '在周围喷射 1 处猛火区域，持续 2.5 秒造成灼烧伤害',
        damage: 12,
        cooldownMs: 1600,
        projectileCount: 1,
        projectileSpeed: 0,
        pierce: 999,
        range: 200,
        durationMs: 2500,
        radius: 65,
        effects: [{ type: 'burn', value: 6, durationMs: 2000, tickIntervalMs: 400 }],
      },
      {
        level: 2,
        descriptionKey: '喷射 2 处火域，范围扩大，伤害提升至 20/跳',
        damage: 20,
        cooldownMs: 1400,
        projectileCount: 2,
        projectileSpeed: 0,
        pierce: 999,
        range: 220,
        durationMs: 3000,
        radius: 80,
        effects: [{ type: 'burn', value: 10, durationMs: 2500, tickIntervalMs: 400 }],
      },
      {
        level: 3,
        descriptionKey: '喷射 3 处巨大火域，伤害 32/跳，灼烧伤害大幅跃升',
        damage: 32,
        cooldownMs: 1200,
        projectileCount: 3,
        projectileSpeed: 0,
        pierce: 999,
        range: 250,
        durationMs: 3500,
        radius: 95,
        effects: [{ type: 'burn', value: 15, durationMs: 3000, tickIntervalMs: 350 }],
      },
    ],
  }),

  seasoning_jar: WeaponDefinitionSchema.parse({
    id: 'seasoning_jar',
    nameKey: '八宝调料瓶',
    descriptionKey: '围绕玩家旋转护体，撞击近身妖魔',
    tags: ['orbit', 'defense'],
    attackPattern: 'orbit',
    targeting: 'forward',
    rarity: 'rare',
    cost: 14,
    color: '#2a9d8f',
    assetKey: 'weapon_seasoning_jar',
    levels: [
      {
        level: 1,
        descriptionKey: '召唤 2 个调料瓶环绕护体，碰撞造成 20 伤害与击退',
        damage: 20,
        cooldownMs: 3000,
        projectileCount: 2,
        projectileSpeed: 2.2,
        pierce: 999,
        range: 90,
        durationMs: 999999,
        radius: 15,
        effects: [{ type: 'knockback', value: 80 }],
      },
      {
        level: 2,
        descriptionKey: '调料瓶数量 +1 (共3个)，旋转速度与伤害提升至 32',
        damage: 32,
        cooldownMs: 3000,
        projectileCount: 3,
        projectileSpeed: 2.8,
        pierce: 999,
        range: 105,
        durationMs: 999999,
        radius: 17,
        effects: [{ type: 'knockback', value: 110 }],
      },
      {
        level: 3,
        descriptionKey: '调料瓶数量 +1 (共4个)，伤害 46，形成密不透风的调料结界',
        damage: 46,
        cooldownMs: 3000,
        projectileCount: 4,
        projectileSpeed: 3.4,
        pierce: 999,
        range: 120,
        durationMs: 999999,
        radius: 19,
        effects: [{ type: 'knockback', value: 140 }],
      },
    ],
  }),

  service_bell: WeaponDefinitionSchema.parse({
    id: 'service_bell',
    nameKey: '唤灵上菜铃',
    descriptionKey: '摇动铜铃召唤帮厨小幽灵自动追击敌人',
    tags: ['summon', 'economy'],
    attackPattern: 'summon',
    targeting: 'nearest',
    rarity: 'epic',
    cost: 18,
    color: '#9d4edd',
    assetKey: 'weapon_service_bell',
    levels: [
      {
        level: 1,
        descriptionKey: '召唤 1 只帮厨小幽灵巡航追杀敌人，造成 16 伤害',
        damage: 16,
        cooldownMs: 3500,
        projectileCount: 1,
        projectileSpeed: 160,
        pierce: 999,
        range: 260,
        durationMs: 6000,
        radius: 20,
        effects: [{ type: 'knockback', value: 50 }],
      },
      {
        level: 2,
        descriptionKey: '同时召唤 2 只帮厨幽灵，幽灵移速提升，伤害 26',
        damage: 26,
        cooldownMs: 3000,
        projectileCount: 2,
        projectileSpeed: 180,
        pierce: 999,
        range: 300,
        durationMs: 7000,
        radius: 22,
        effects: [{ type: 'knockback', value: 70 }],
      },
      {
        level: 3,
        descriptionKey: '同时召唤 3 只帮厨幽灵，伤害 40，幽灵移速与索敌范围大幅增强',
        damage: 40,
        cooldownMs: 2500,
        projectileCount: 3,
        projectileSpeed: 210,
        pierce: 999,
        range: 340,
        durationMs: 8000,
        radius: 24,
        effects: [{ type: 'knockback', value: 90 }],
      },
    ],
  }),

  dragon_spatula: WeaponDefinitionSchema.parse({
    id: 'dragon_spatula',
    nameKey: '八卦游龙铲',
    descriptionKey: '掷出回旋飞铲，穿透敌人并在折返回程造成双倍撕裂',
    tags: ['cleaver', 'melee', 'crit'],
    attackPattern: 'boomerang',
    targeting: 'nearest',
    rarity: 'rare',
    cost: 14,
    color: '#ffd166',
    assetKey: 'weapon_dragon_spatula',
    levels: [
      {
        level: 1,
        descriptionKey: '掷出 1 把回旋金铲，穿透造成 35 伤害，回程双倍伤害',
        damage: 35,
        cooldownMs: 1100,
        projectileCount: 1,
        projectileSpeed: 450,
        pierce: 999,
        range: 360,
        durationMs: 1600,
        radius: 16,
        effects: [{ type: 'knockback', value: 100 }],
      },
      {
        level: 2,
        descriptionKey: '回旋铲数量 +1，伤害提升至 52，范围与移速提升',
        damage: 52,
        cooldownMs: 950,
        projectileCount: 2,
        projectileSpeed: 500,
        pierce: 999,
        range: 400,
        durationMs: 1600,
        radius: 18,
        effects: [{ type: 'knockback', value: 130 }],
      },
      {
        level: 3,
        descriptionKey: '回旋铲数量 +1 (共3把)，伤害 75，回程附带猛火爆炒',
        damage: 75,
        cooldownMs: 800,
        projectileCount: 3,
        projectileSpeed: 540,
        pierce: 999,
        range: 440,
        durationMs: 1600,
        radius: 20,
        effects: [
          { type: 'knockback', value: 160 },
          { type: 'burn', value: 12, durationMs: 2500, tickIntervalMs: 500 },
        ],
      },
    ],
  }),

  popcorn_popper: WeaponDefinitionSchema.parse({
    id: 'popcorn_popper',
    nameKey: '金玉爆米花机',
    descriptionKey: '迫击高抛玉米金粒，落地爆散为弹跳金米花群',
    tags: ['fire', 'projectile', 'economy'],
    attackPattern: 'mortar',
    targeting: 'nearest',
    rarity: 'rare',
    cost: 14,
    color: '#ffe66d',
    assetKey: 'weapon_popcorn_popper',
    levels: [
      {
        level: 1,
        descriptionKey: '抛射 1 团玉米粒，落地爆裂为 5 颗弹跳爆米花，每颗造成 20 伤害',
        damage: 20,
        cooldownMs: 1300,
        projectileCount: 1,
        projectileSpeed: 320,
        pierce: 1,
        range: 320,
        durationMs: 1800,
        radius: 14,
        effects: [{ type: 'knockback', value: 80 }],
      },
      {
        level: 2,
        descriptionKey: '抛射数量 +1，爆米花分裂数量增加，伤害提升至 32',
        damage: 32,
        cooldownMs: 1150,
        projectileCount: 2,
        projectileSpeed: 350,
        pierce: 1,
        range: 360,
        durationMs: 2000,
        radius: 16,
        effects: [{ type: 'knockback', value: 100 }],
      },
      {
        level: 3,
        descriptionKey: '抛射 3 团高爆玉米粒，爆裂火花附带范围灼烧',
        damage: 48,
        cooldownMs: 950,
        projectileCount: 3,
        projectileSpeed: 380,
        pierce: 2,
        range: 400,
        durationMs: 2200,
        radius: 18,
        effects: [
          { type: 'knockback', value: 120 },
          { type: 'burn', value: 10, durationMs: 2000, tickIntervalMs: 500 },
        ],
      },
    ],
  }),

  jade_teapot: WeaponDefinitionSchema.parse({
    id: 'jade_teapot',
    nameKey: '冰魄玉泉壶',
    descriptionKey: '持续喷涌扇形冰霜茶雾射线，高频穿透并深度减速',
    tags: ['ice', 'defense', 'speed'],
    attackPattern: 'beam',
    targeting: 'nearest',
    rarity: 'epic',
    cost: 16,
    color: '#48cae4',
    assetKey: 'weapon_jade_teapot',
    levels: [
      {
        level: 1,
        descriptionKey: '前方喷射极寒茶雾射线，每秒造成 45 穿透伤害并减速 40%',
        damage: 18,
        cooldownMs: 350,
        projectileCount: 1,
        projectileSpeed: 420,
        pierce: 999,
        range: 240,
        durationMs: 400,
        radius: 26,
        effects: [{ type: 'slow', value: 0.4, durationMs: 1500 }],
      },
      {
        level: 2,
        descriptionKey: '茶雾范围加宽，伤害提升至 28，减速提升至 55%',
        damage: 28,
        cooldownMs: 300,
        projectileCount: 2,
        projectileSpeed: 450,
        pierce: 999,
        range: 280,
        durationMs: 450,
        radius: 32,
        effects: [{ type: 'slow', value: 0.55, durationMs: 2000 }],
      },
      {
        level: 3,
        descriptionKey: '三道冰魄茶雾洪流，伤害 42，敌人冻结并遭受击退',
        damage: 42,
        cooldownMs: 260,
        projectileCount: 3,
        projectileSpeed: 480,
        pierce: 999,
        range: 320,
        durationMs: 500,
        radius: 38,
        effects: [
          { type: 'slow', value: 0.7, durationMs: 2500 },
          { type: 'knockback', value: 90 },
        ],
      },
    ],
  }),

  flavor_vortex: WeaponDefinitionSchema.parse({
    id: 'flavor_vortex',
    nameKey: '乾坤聚味瓮',
    descriptionKey: '在前方生成微缩聚味引力黑洞，持续牵引聚集并绞碎妖怪',
    tags: ['oil', 'ferment', 'sugar'],
    attackPattern: 'vortex',
    targeting: 'nearest',
    rarity: 'epic',
    cost: 18,
    color: '#9d4edd',
    assetKey: 'weapon_flavor_vortex',
    levels: [
      {
        level: 1,
        descriptionKey: '生成 1 个聚味引力旋涡，持续 3 秒牵引怪物并造成高频绞碎伤害',
        damage: 15,
        cooldownMs: 2400,
        projectileCount: 1,
        projectileSpeed: 0,
        pierce: 999,
        range: 260,
        durationMs: 3000,
        radius: 95,
        effects: [{ type: 'knockback', value: -120 }], // 负击退 = 引力吸入
      },
      {
        level: 2,
        descriptionKey: '旋涡引力与范围提升，持续时间增至 4 秒，伤害提升至 25',
        damage: 25,
        cooldownMs: 2200,
        projectileCount: 1,
        projectileSpeed: 0,
        pierce: 999,
        range: 300,
        durationMs: 4000,
        radius: 120,
        effects: [{ type: 'knockback', value: -160 }],
      },
      {
        level: 3,
        descriptionKey: '同时生成 2 个超强引力黑洞，伤害 38，附带深度腐蚀撕裂',
        damage: 38,
        cooldownMs: 1900,
        projectileCount: 2,
        projectileSpeed: 0,
        pierce: 999,
        range: 340,
        durationMs: 4500,
        radius: 140,
        effects: [
          { type: 'knockback', value: -200 },
          { type: 'burn', value: 8, durationMs: 2000, tickIntervalMs: 400 },
        ],
      },
    ],
  }),
};
