import { CharacterDefinition, CharacterDefinitionSchema } from '../schemas/character';

export const CHARACTERS: Record<string, CharacterDefinition> = {
  wok_master: CharacterDefinitionSchema.parse({
    id: 'wok_master',
    nameKey: '铁锅宗师·大牛',
    titleKey: '夜市掌勺宗师',
    descriptionKey: '大排档镇店大厨。拥有 6 个神兵槽位，生命与护甲出众，专精火候与近战猛攻。',
    startingWeaponId: 'iron_wok',
    tags: ['wok', 'fire', 'melee', 'defense'],
    maxWeapons: 6,
    baseStats: {
      maxHp: 120,
      moveSpeed: 190,
      damageMultiplier: 1.1,
      attackSpeedMultiplier: 1.0,
      critChance: 0.05,
      critMultiplier: 1.5,
      pickupRadius: 70,
      armor: 2,
      dodge: 0.05,
      hpRegen: 1,
      lifesteal: 0,
      meleeDamage: 3,
      rangedDamage: 0,
      elementalDamage: 2,
      harvest: 5,
      luck: 0,
      engineering: 0,
    },
    assetKey: 'char_wok_master',
  }),

  one_handed: CharacterDefinitionSchema.parse({
    id: 'one_handed',
    nameKey: '独臂快刀·阿飞',
    titleKey: '单刀断水流',
    descriptionKey: '【规则颠覆】只能装备 1 把武器，但享有 +200% 攻速与 +100% 全伤害，刀光连绵不绝！',
    startingWeaponId: 'cleaver',
    tags: ['cleaver', 'melee', 'crit', 'speed'],
    maxWeapons: 1,
    baseStats: {
      maxHp: 100,
      moveSpeed: 220,
      damageMultiplier: 2.0,
      attackSpeedMultiplier: 3.0,
      critChance: 0.15,
      critMultiplier: 1.8,
      pickupRadius: 80,
      armor: 1,
      dodge: 0.15,
      hpRegen: 0,
      lifesteal: 1,
      meleeDamage: 10,
      rangedDamage: 0,
      elementalDamage: 0,
      harvest: 0,
      luck: 5,
      engineering: 0,
    },
    assetKey: 'char_wok_master',
    specialTrait: 'one_handed',
  }),

  six_armed: CharacterDefinitionSchema.parse({
    id: 'six_armed',
    nameKey: '六臂神童·童童',
    titleKey: '多宝神厨',
    descriptionKey: '【极致火力】开局即享 6 武器槽位，武器购买价格 -20%，但初始护甲 -2，容错较低。',
    startingWeaponId: 'bamboo_skewer',
    tags: ['skewer', 'projectile', 'economy'],
    maxWeapons: 6,
    baseStats: {
      maxHp: 90,
      moveSpeed: 200,
      damageMultiplier: 1.0,
      attackSpeedMultiplier: 1.1,
      critChance: 0.08,
      critMultiplier: 1.5,
      pickupRadius: 85,
      armor: -2,
      dodge: 0.05,
      hpRegen: 0,
      lifesteal: 0,
      meleeDamage: 0,
      rangedDamage: 3,
      elementalDamage: 0,
      harvest: 10,
      luck: 10,
      engineering: 2,
    },
    assetKey: 'char_skewer_griller',
    specialTrait: 'six_armed',
  }),

  investor: CharacterDefinitionSchema.parse({
    id: 'investor',
    nameKey: '守财掌柜·钱百万',
    titleKey: '夜市大掌柜',
    descriptionKey: '【复利经营】初始【收获】+25，每波食材利息翻倍，且每持有 25 份食材伤害提升 1%！',
    startingWeaponId: 'seasoning_jar',
    tags: ['economy', 'orbit', 'sugar'],
    maxWeapons: 6,
    baseStats: {
      maxHp: 95,
      moveSpeed: 195,
      damageMultiplier: 0.9,
      attackSpeedMultiplier: 1.0,
      critChance: 0.05,
      critMultiplier: 1.5,
      pickupRadius: 110,
      armor: 0,
      dodge: 0.05,
      hpRegen: 0,
      lifesteal: 0,
      meleeDamage: 0,
      rangedDamage: 0,
      elementalDamage: 0,
      harvest: 25,
      luck: 15,
      engineering: 0,
    },
    assetKey: 'char_cold_brewer',
    specialTrait: 'investor',
  }),

  herbalist: CharacterDefinitionSchema.parse({
    id: 'herbalist',
    nameKey: '药膳医仙·素问',
    titleKey: '妙手回春',
    descriptionKey: '【以柔克刚】生命秒回 +5，受到伤害后爆发治愈药香，所有攻击附加持续毒伤与火伤。',
    startingWeaponId: 'stove_flame',
    tags: ['fire', 'ice', 'defense', 'ferment'],
    maxWeapons: 6,
    baseStats: {
      maxHp: 130,
      moveSpeed: 185,
      damageMultiplier: 1.0,
      attackSpeedMultiplier: 0.95,
      critChance: 0.0,
      critMultiplier: 1.2,
      pickupRadius: 75,
      armor: 3,
      dodge: 0.1,
      hpRegen: 5,
      lifesteal: 2,
      meleeDamage: 0,
      rangedDamage: 0,
      elementalDamage: 8,
      harvest: 5,
      luck: 0,
      engineering: 3,
    },
    assetKey: 'char_cold_brewer',
    specialTrait: 'herbalist',
  }),
};
